server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:EcommerceDB
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
  sql:
    init.mode: always